import Head from 'next/head'
import Image from 'next/image'
import {GraphQLClient, gql} from 'graphql-request'
import BlogCard from '../components/BlogCard'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

import 'bootstrap/dist/css/bootstrap.css'

const graphcms = new GraphQLClient(
  "https://api-eu-west-2.hygraph.com/v2/cl8bll9nl0xgr01t7cob8btmg/master"
);

const QUERY = gql`
{
  posts {
    id,
    title,
    datePublished,
    slug,
    coverPhoto {
      id,
      url
    },
    preview,
    content{
      html
    },
    author{
      name,
      avatar{
        url
      }
    }
  }
}
`;

export async function getStaticProps(){
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate:10,
  };
}

export default function Home(posts) {
  return (
    <div>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar/>

        <header>
          <style jsx>{`
          @font-face {
              font-family: 'Sucrose Bold Two';
              src: url('https://s3-us-west-2.amazonaws.com/s.cdpn.io/4273/sucrose.woff2') format('woff2');
              }
          @font-face {
              font-family: 'IM Fell French Canon Pro';
              src: url('https://s3-us-west-2.amazonaws.com/s.cdpn.io/4273/im-fell-french-canon-pro.woff2') format('woff2');
          }
          * {
            box-sizing: border-box;
          }
          body {
            margin: 0;
          }
          header { 
            background: url(/wallpaper_3.jpg) no-repeat;
            padding-top: 61.93333333%;
            background-size: cover;
            font-family: 'Sucrose Bold Two';
          }
          header img {
            position: absolute;
            top: 0;
            right: 0;
            width: 45.8%;
          }
          header h1 { 
            position: absolute;
            top: 24rem;
            right: 2rem;
            font-size: 12vw;
            line-height: .8;
            margin-top: 100;
            text-align: center;
          }
          header h1 span {
            display: block;
            font-size: 8.75vw;
          }`}
          </style>

          <h1>Higher Life Center</h1>
          {/* <img src="/wallpaper_4.jpg"/> */}
        </header>

      </div>
      <Footer/>
    </div>
  )
}
