import Head from 'next/head'
import Image from 'next/image'
import {GraphQLClient, gql} from 'graphql-request'
import BlogCard from '../components/BlogCard'

const graphcms = new GraphQLClient(
  "https://api-eu-west-2.hygraph.com/v2/cl8bll9nl0xgr01t7cob8btmg/master"
);

const QUERY = gql`
{
  posts {
    id,
    title,
    datePublished,
    slug,
    coverPhoto {
      id,
      url
    },
    preview,
    content{
      html
    },
    author{
      name,
      avatar{
        url
      }
    }
  }
}
`;

export async function getStaticProps(){
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate:10,
  };
}

export default function Home(posts) {
  return (
    <div className={"container"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={"main"}>
        <div>
        <section>
            <article>
              <div className="article-wrapper">
                <div className="blog-label">
                <div className="home-label">
                <h4 className="home-label-title">MEDITATION TIMES</h4>
                </div>
                </div>

                {posts.posts.map((post) => (
          <BlogCard
            title={post.title}
            preview={post.preview}
            author={post.author}
            coverPhoto={post.coverPhoto}
            key={post.id}
            datePublished={post.datePublished}
            slug={post.slug}
          />
        ))}
        {console.log(posts.posts)}

              </div>
            </article>
            <aside>
              <div className="aside-about">
                <div className="home-label aside-label">
                  <h4 className="home-label-title">WHAT IS THE MEDITATION TIMES</h4>
                </div>
                <div className="aside-content-home">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum nam neque non rem rerum ipsa in doloremque aspernatur eius iste, cupiditate repudiandae, quis laboriosam ipsam, architecto sed dolorem quos enim optio eveniet dignissimos aliquam temporibus? Laboriosam ipsa veritatis nemo ab.
                </div>
              </div>
              <div className="aside-work">
                <div className="home-label aside-label">
                  <h4 className="home-label-title">WORSHIP WITH US</h4>
                </div>
                <div className="aside-content-home">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum nam neque non rem rerum ipsa in doloremque aspernatur eius iste, cupiditate repudiandae, quis laboriosam ipsam, architecto sed dolorem quos enim optio eveniet dignissimos aliquam temporibus? Laboriosam ipsa veritatis nemo ab.
                </div>
              </div>
            </aside>
        </section>
        </div>
      </main>

      <footer className={"footer"}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={"logo"}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
